
// array of objects representing each word and their data
// athor: cohen creighton
const wordsData=[
    {word:"ni'n",description:"I",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nin.wav"},
    {word:"ki'l",description:"you",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kil.wav"},
    {word:"teluisi",description:"My name is...",
    image:"https://thumbs.dreamstime.com/b/hand-like-icon-isolated-white-background-vector-illustration-235659506.jpg",
    audio:"/audio/teluisi.wav"},
    {word:"aqq",description:"and",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/aqq.wav"},
    {word:"mijisi",description:"eat",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/mijisi.wav"},
    {word:"wiktm",description:"I like the taste of it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wiktm.wav"},
    {word:"kesalk",description:"I love...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesalk.wav"},
    {word:"l'tu",description:"Make it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/ltu.wav"},
    {word:"eliey",description:"I am going.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/eliey.wav"},
    {word:"nemitu",description:"I see it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nemitu.wav"},
    {word:"kesatm",description:"I like...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesatm.wav"},
    {word:"wejiey",description:"I am coming from...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wejiey.wav"},
    {word:"ta'ta",description:"Dad",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/tata.wav"},
    {word:"kiju'",description:"Grandmother or Mother",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kiju.wav"},
    {word:"nekm",description:"him or her",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nekm.wav"},
    {word:"ala'tu",description:"I have it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/alatu.wav"},
    {word:"ula",description:"Look at this.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/ula.wav"},
    {word:"kesalul",description:"I love you.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesalul.wav"},
    {word:"welta'si",description:"I am happy.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/weltasi.wav"},
    {word:"wen",description:"Who",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wen.wav"}
  ];

export default wordsData;