
// array of objects representing each word and their data
// athor: cohen creighton
const wordsData=[
    {id:1,word:"ni'n",description:"I",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nin.wav"},
    {id:2,word:"ki'l",description:"you",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kil.wav"},
    {id:3,word:"teluisi",description:"My name is...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/teluisi.wav"},
    {id:4,word:"aqq",description:"and",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/aqq.wav"},
    {id:5,word:"mijisi",description:"eat",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/mijisi.wav"},
    {id:6,word:"wiktm",description:"I like the taste of it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wiktm.wav"},
    {id:7,word:"kesalk",description:"I love...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesalk.wav"},
    {id:8,word:"l'tu",description:"Make it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/ltu.wav"},
    {id:9,word:"eliey",description:"I am going.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/eliey.wav"},
    {id:10,word:"nemitu",description:"I see it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nemitu.wav"},
    {id:11,word:"kesatm",description:"I like...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesatm.wav"},
    {id:12,word:"wejiey",description:"I am coming from...",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wejiey.wav"},
    {id:13,word:"ta'ta",description:"Dad",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/tata.wav"},
    {id:14,word:"kiju'",description:"Grandmother or Mother",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kiju.wav"},
    {id:15,word:"nekm",description:"him or her",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/nekm.wav"},
    {id:16,word:"ala'tu",description:"I have it.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/alatu.wav"},
    {id:17,word:"ula",description:"Look at this.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/ula.wav"},
    {id:18,word:"kesalul",description:"I love you.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/kesalul.wav"},
    {id:19,word:"welta'si",description:"I am happy.",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/weltasi.wav"},
    {id:20,word:"wen",description:"Who",
    image:"https://cdn.vectorstock.com/i/500p/62/66/wave-hand-hello-sign-greeting-gesture-isolated-vector-30246266.jpg",
    audio:"/audio/wen.wav"},
  ];

export default wordsData;