
// array of objects representing each word and their data
// author: cohen creighton
const wordsData=[
    {id:1,word:"ni'n",description:"I",
    image:"/images/I.jpeg",
    audio:"/audio/nin.wav"},
    {id:2,word:"ki'l",description:"you",
    image:"/images/you.jpeg",
    audio:"/audio/kil.wav"},
    {id:3,word:"teluisi",description:"My name is...",
    image:"/images/My name is.jpeg",
    audio:"/audio/teluisi.wav"},
    {id:4,word:"aqq",description:"and",
    image:"/images/and symbol.jpeg",
    audio:"/audio/aqq.wav"},
    {id:5,word:"mijisi",description:"eat",
    image:"/images/eat.png",
    audio:"/audio/mijisi.wav"},
    {id:6,word:"wiktm",description:"I like the taste of it.",
    image:"/images/taste.jpeg",
    audio:"/audio/wiktm.wav"},
    {id:7,word:"kesalk",description:"I love...",
    image:"/images/I love.jpeg",
    audio:"/audio/kesalk.wav"},
    {id:8,word:"l'tu",description:"Make it.",
    image:"/images/makeit.jpg",
    audio:"/audio/ltu.wav"},
    {id:9,word:"eliey",description:"I am going.",
    image:"/images/going.jpeg",
    audio:"/audio/eliey.wav"},
    {id:10,word:"nemitu",description:"I see it.",
    image:"/images/i see it.jpeg",
    audio:"/audio/nemitu.wav"},
    {id:11,word:"kesatm",description:"I like...",
    image:"/images/I like it.jpeg",
    audio:"/audio/kesatm.wav"},
    {id:12,word:"wejiey",description:"I am coming from...",
    image:"/images/coming.jpeg",
    audio:"/audio/wejiey.wav"},
    {id:13,word:"ta'ta",description:"Dad",
    image:"/images/DAD.jpeg",
    audio:"/audio/tata.wav"},
    {id:14,word:"kiju'",description:"Grandmother or Mother",
    image:"/images/grandmother.jpeg",
    audio:"/audio/kiju.wav"},
    {id:15,word:"nekm",description:"him or her",
    image:"/images/him.jpeg",
    audio:"/audio/nekm.m4a"},
    {id:16,word:"ala'tu",description:"I have it.",
    image:"/images/i have it.jpeg",
    audio:"/audio/alatu.wav"},
    {id:17,word:"ula",description:"Look at this.",
    image:"/images/lookatthis.avif",
    audio:"/audio/ula.wav"},
    {id:18,word:"kesalul",description:"I love you.",
    image:"/images/hug(i Love you).jpg",
    audio:"/audio/kesalul.wav"},
    {id:19,word:"welta'si",description:"I am happy.",
    image:"/images/I am Happy.jpeg",
    audio:"/audio/weltasi.wav"},
    {id:20,word:"wen",description:"Who",
    image:"images/who.jpeg",
    audio:"/audio/wen.m4a"},
  ];

export default wordsData;